name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Go mod tidy
      run: go mod tidy

    - name: Build
      run: |
        go build -v ./... || echo "Build failed with exit code: $?"

    - name: Test
      run: |
        go test -v ./... || echo "Tests failed with exit code: $?"
